export const textItems = [
 { isHeading: true, textId: "instructions.registration.title" },
 { textId: "instructions.registration.1" },
 { textId: "instructions.registration.2" },
 { textId: "instructions.registration.3" },
 { textId: "instructions.registration.4" },
 { textId: "instructions.registration.notification", attrs: { variant: "md" } },
 { textId: "instructions.registration.5", withSpace: true },
 { textId: "instructions.registration.notification2", withSpace: true },
 { textId: "instructions.registration.6", withSpace: true },
 { isHeading: true, textId: "instructions.isRegistered.title" },
 { textId: "instructions.isRegistered.1" },
 { textId: "instructions.isRegistered.2" },
 { textId: "instructions.isRegistered.3", withSpace: true },
 { textId: "instructions.isRegistered.notification", withSpace: true },
 { isHeading: true, textId: "instructions.notification.title" },
 { textId: "instructions.notification.1" },
 { textId: "instructions.notification.2" },
 { textId: "instructions.notification.3" },
 { textId: "instructions.notification.4" },
 { textId: "instructions.notification.5" },
 { textId: "instructions.notification.6" },
 {
  textId: "instructions.notification.warning",
  attrs: {
   color: "var(--main-error-color)",
   bold: true,
  },
  withSpace: true,
 },
];
